apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hc3xnh10s-go
  janus-idp.io/tekton: hc3xnh10s-go
  backstage.io/kubernetes-id: hc3xnh10s-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hc3xnh10s-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
