apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: hc3xnh10s-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:72365885e9fa17fbcb2ba2b2fd44d8bd107b3749@sha256:be59ed268228fbc6a057d9b6de4e987af820cb1f1d6dff734e1c4d364cec0f82
          name: container-image
